const ACHIEVEMENT_DEFINITIONS = [
  {
    id: "community_join",
    name: "Chao mung den cong dong",
    description: "Hoan tat dang ky va tro thanh thanh vien cua HTTD.",
    icon: "🤝",
    color: "#10b981",
    category: "social",
    points: 10,
    rarity: "common",
    condition: { type: "custom", value: 1, operator: ">=" },
    unlockMessage: "Chao mung ban den voi cong dong Hoc Tap Thu Duc!",
    isHidden: false
  },
  {
    id: "first_login",
    name: "Lan dau dang nhap",
    description: "Dang nhap vao he thong lan dau tien.",
    icon: "✨",
    color: "#8b5cf6",
    category: "milestone",
    points: 5,
    rarity: "common",
    condition: { type: "custom", value: 1, operator: ">=" },
    unlockMessage: "Hanh trinh hoc tap cua ban da bat dau!",
    isHidden: false
  },
  {
    id: "first_lesson",
    name: "Buoc dau tien",
    description: "Hoan thanh bai hoc dau tien.",
    icon: "🎓",
    color: "#3b82f6",
    category: "learning",
    points: 10,
    rarity: "common",
    condition: { type: "lessons_completed", value: 1, operator: ">=" },
    unlockMessage: "Ban da hoan thanh bai hoc dau tien!",
    isHidden: false
  },
  {
    id: "lessons_10",
    name: "Hoc vien cham chi",
    description: "Hoan thanh 10 bai hoc.",
    icon: "📚",
    color: "#6366f1",
    category: "learning",
    points: 25,
    rarity: "rare",
    condition: { type: "lessons_completed", value: 10, operator: ">=" },
    unlockMessage: "10 bai hoc da xong. Tiep tuc giu nhip nay nhe!",
    isHidden: false
  },
  {
    id: "lessons_25",
    name: "Chuyen gia tap su",
    description: "Hoan thanh 25 bai hoc.",
    icon: "🏆",
    color: "#f59e0b",
    category: "learning",
    points: 50,
    rarity: "epic",
    condition: { type: "lessons_completed", value: 25, operator: ">=" },
    unlockMessage: "Ban da cham moc 25 bai hoc!",
    isHidden: false
  },
  {
    id: "lessons_50",
    name: "Thac si kien thuc",
    description: "Hoan thanh 50 bai hoc.",
    icon: "👑",
    color: "#ec4899",
    category: "learning",
    points: 100,
    rarity: "epic",
    condition: { type: "lessons_completed", value: 50, operator: ">=" },
    unlockMessage: "50 bai hoc la cot moc rat an tuong!",
    isHidden: false
  },
  {
    id: "lessons_100",
    name: "Huyen thoai hoc tap",
    description: "Hoan thanh 100 bai hoc.",
    icon: "🎯",
    color: "#dc2626",
    category: "learning",
    points: 200,
    rarity: "legendary",
    condition: { type: "lessons_completed", value: 100, operator: ">=" },
    unlockMessage: "100 bai hoc. Ban that su la mot huyen thoai!",
    isHidden: true
  },
  {
    id: "points_100",
    name: "Thu thap nang luong",
    description: "Dat 100 diem hoc tap.",
    icon: "⚡",
    color: "#14b8a6",
    category: "engagement",
    points: 15,
    rarity: "common",
    condition: { type: "points_reached", value: 100, operator: ">=" },
    unlockMessage: "Ban da cham moc 100 diem hoc tap!",
    isHidden: false
  },
  {
    id: "points_500",
    name: "Kho bau diem so",
    description: "Dat 500 diem hoc tap.",
    icon: "💎",
    color: "#06b6d4",
    category: "engagement",
    points: 50,
    rarity: "rare",
    condition: { type: "points_reached", value: 500, operator: ">=" },
    unlockMessage: "500 diem la mot cot moc dang tu hao!",
    isHidden: false
  },
  {
    id: "points_1000",
    name: "Ngoi sao lap lanh",
    description: "Dat 1000 diem hoc tap.",
    icon: "🌟",
    color: "#f97316",
    category: "engagement",
    points: 100,
    rarity: "epic",
    condition: { type: "points_reached", value: 1000, operator: ">=" },
    unlockMessage: "1000 diem. Ban dang toa sang!",
    isHidden: false
  },
  {
    id: "streak_7",
    name: "Chuoi 7 ngay",
    description: "Duy tri streak hoc tap 7 ngay lien tiep.",
    icon: "🔥",
    color: "#ef4444",
    category: "challenge",
    points: 35,
    rarity: "rare",
    condition: { type: "streak_days", value: 7, operator: ">=" },
    unlockMessage: "7 ngay lien tiep. Rat kien tri!",
    isHidden: false
  },
  {
    id: "streak_30",
    name: "Vua kien tri",
    description: "Duy tri streak hoc tap 30 ngay lien tiep.",
    icon: "💪",
    color: "#d946ef",
    category: "challenge",
    points: 100,
    rarity: "epic",
    condition: { type: "streak_days", value: 30, operator: ">=" },
    unlockMessage: "Mot thang lien tuc. Ban qua ben bi!",
    isHidden: false
  },
  {
    id: "streak_100",
    name: "Khong the ngan can",
    description: "Duy tri streak hoc tap 100 ngay lien tiep.",
    icon: "🚀",
    color: "#7c3aed",
    category: "challenge",
    points: 300,
    rarity: "legendary",
    condition: { type: "streak_days", value: 100, operator: ">=" },
    unlockMessage: "100 ngay streak. Ban khong the ngan can!",
    isHidden: true
  },
  {
    id: "level_10",
    name: "Canh gioi cao thu",
    description: "Dat level 10.",
    icon: "🎖️",
    color: "#f59e0b",
    category: "milestone",
    points: 150,
    rarity: "epic",
    condition: { type: "level_reached", value: 10, operator: ">=" },
    unlockMessage: "Ban da dat level 10!",
    isHidden: false
  },
  {
    id: "first_plant",
    name: "Nong dan tap su",
    description: "Trong cay dau tien trong vuon.",
    icon: "🌱",
    color: "#22c55e",
    category: "engagement",
    points: 10,
    rarity: "common",
    condition: { type: "plants_planted", value: 1, operator: ">=" },
    unlockMessage: "Vuon cua ban da co cay dau tien!",
    isHidden: false
  },
  {
    id: "plants_10",
    name: "Vuon dang len",
    description: "Trong tong cong 10 cay.",
    icon: "🌿",
    color: "#16a34a",
    category: "engagement",
    points: 30,
    rarity: "rare",
    condition: { type: "plants_planted", value: 10, operator: ">=" },
    unlockMessage: "Ban da trong 10 cay trong vuon!",
    isHidden: false
  },
  {
    id: "plants_50",
    name: "Ty phu xanh",
    description: "Trong tong cong 50 cay.",
    icon: "🌳",
    color: "#15803d",
    category: "engagement",
    points: 80,
    rarity: "epic",
    condition: { type: "plants_planted", value: 50, operator: ">=" },
    unlockMessage: "Vuon cua ban dang tro thanh mot khu rung nho!",
    isHidden: false
  },
  {
    id: "first_harvest",
    name: "Mua thu hoach dau tien",
    description: "Thu hoach cay dau tien.",
    icon: "🍎",
    color: "#dc2626",
    category: "engagement",
    points: 15,
    rarity: "common",
    condition: { type: "plants_harvested", value: 1, operator: ">=" },
    unlockMessage: "Ban da thu hoach thanh cong lan dau!",
    isHidden: false
  },
  {
    id: "harvest_20",
    name: "Nong dan chinh hieu",
    description: "Thu hoach 20 lan.",
    icon: "🚜",
    color: "#b45309",
    category: "engagement",
    points: 60,
    rarity: "rare",
    condition: { type: "plants_harvested", value: 20, operator: ">=" },
    unlockMessage: "20 lan thu hoach. Ban dang rat mat tay!",
    isHidden: false
  },
  {
    id: "harvest_100",
    name: "Vuon vang boi thu",
    description: "Thu hoach 100 lan.",
    icon: "🌽",
    color: "#d97706",
    category: "engagement",
    points: 120,
    rarity: "epic",
    condition: { type: "plants_harvested", value: 100, operator: ">=" },
    unlockMessage: "100 lan thu hoach. Vuon cua ban qua on dinh!",
    isHidden: false
  },
  {
    id: "gold_500",
    name: "Kho vang mini",
    description: "Thu thap 500 vang tu vuon.",
    icon: "💰",
    color: "#f59e0b",
    category: "engagement",
    points: 40,
    rarity: "rare",
    condition: { type: "gold_collected", value: 500, operator: ">=" },
    unlockMessage: "Vuon cua ban bat dau sinh loi ro rang!",
    isHidden: false
  },
  {
    id: "gold_1000",
    name: "Nha giau nong trai",
    description: "Thu thap 1000 vang tu vuon.",
    icon: "🏆",
    color: "#fbbf24",
    category: "milestone",
    points: 100,
    rarity: "epic",
    condition: { type: "gold_collected", value: 1000, operator: ">=" },
    unlockMessage: "1000 vang tu vuon. Rat an tuong!",
    isHidden: false
  },
  {
    id: "watered_20",
    name: "Ban tay mat",
    description: "Tuoi cay 20 lan.",
    icon: "💧",
    color: "#0ea5e9",
    category: "engagement",
    points: 20,
    rarity: "common",
    condition: { type: "plants_watered", value: 20, operator: ">=" },
    unlockMessage: "Cay coi cua ban dang duoc cham soc rat tot!",
    isHidden: false
  },
  {
    id: "watered_100",
    name: "Sieu nhan tuoi cay",
    description: "Tuoi cay 100 lan.",
    icon: "🌧️",
    color: "#0284c7",
    category: "engagement",
    points: 40,
    rarity: "rare",
    condition: { type: "plants_watered", value: 100, operator: ">=" },
    unlockMessage: "100 lan tuoi cay. Ban rat co tam voi khu vuon!",
    isHidden: false
  },
  {
    id: "decoration_master",
    name: "Nghe nhan trang tri",
    description: "Dat 20 vat trang tri trong vuon.",
    icon: "🎨",
    color: "#ec4899",
    category: "engagement",
    points: 50,
    rarity: "rare",
    condition: { type: "decorations_placed", value: 20, operator: ">=" },
    unlockMessage: "Vuon cua ban da co phong cach rieng rat ro rang!",
    isHidden: false
  }
].map((achievement) => ({
  ...achievement,
  isActive: achievement.isActive !== false
}));

module.exports = {
  ACHIEVEMENT_DEFINITIONS
};
