const ACHIEVEMENT_DEFINITIONS = [
  {
    id: "community_join",
    name: "Chào mừng đến cộng đồng",
    description: "Hoàn tất đăng ký và trở thành thành viên của HTTD.",
    icon: "🤝",
    color: "#10b981",
    category: "social",
    points: 10,
    rarity: "common",
    condition: { type: "custom", value: 1, operator: ">=" },
    unlockMessage: "Chào mừng bạn đến với cộng đồng Học Tập Thủ Đức!",
    isHidden: false
  },
  {
    id: "first_login",
    name: "Lần đầu đăng nhập",
    description: "Đăng nhập vào hệ thống lần đầu tiên.",
    icon: "✨",
    color: "#8b5cf6",
    category: "milestone",
    points: 5,
    rarity: "common",
    condition: { type: "custom", value: 1, operator: ">=" },
    unlockMessage: "Hành trình học tập của bạn đã bắt đầu!",
    isHidden: false
  },
  {
    id: "first_lesson",
    name: "Bước đầu tiên",
    description: "Hoàn thành bài học đầu tiên.",
    icon: "🎓",
    color: "#3b82f6",
    category: "learning",
    points: 10,
    rarity: "common",
    condition: { type: "lessons_completed", value: 1, operator: ">=" },
    unlockMessage: "Bạn đã hoàn thành bài học đầu tiên!",
    isHidden: false
  },
  {
    id: "lessons_10",
    name: "Học viên chăm chỉ",
    description: "Hoàn thành 10 bài học.",
    icon: "📚",
    color: "#6366f1",
    category: "learning",
    points: 25,
    rarity: "rare",
    condition: { type: "lessons_completed", value: 10, operator: ">=" },
    unlockMessage: "10 bài học đã xong. Tiếp tục giữ nhịp này nhé!",
    isHidden: false
  },
  {
    id: "lessons_25",
    name: "Chuyên gia tập sự",
    description: "Hoàn thành 25 bài học.",
    icon: "🏆",
    color: "#f59e0b",
    category: "learning",
    points: 50,
    rarity: "epic",
    condition: { type: "lessons_completed", value: 25, operator: ">=" },
    unlockMessage: "Bạn đã chạm mốc 25 bài học!",
    isHidden: false
  },
  {
    id: "lessons_50",
    name: "Thạc sĩ kiến thức",
    description: "Hoàn thành 50 bài học.",
    icon: "👑",
    color: "#ec4899",
    category: "learning",
    points: 100,
    rarity: "epic",
    condition: { type: "lessons_completed", value: 50, operator: ">=" },
    unlockMessage: "50 bài học là cột mốc rất ấn tượng!",
    isHidden: false
  },
  {
    id: "lessons_100",
    name: "Huyền thoại học tập",
    description: "Hoàn thành 100 bài học.",
    icon: "🎯",
    color: "#dc2626",
    category: "learning",
    points: 200,
    rarity: "legendary",
    condition: { type: "lessons_completed", value: 100, operator: ">=" },
    unlockMessage: "100 bài học. Bạn thật sự là một huyền thoại!",
    isHidden: true
  },
  {
    id: "points_100",
    name: "Thu thập năng lượng",
    description: "Đạt 100 điểm học tập.",
    icon: "⚡",
    color: "#14b8a6",
    category: "engagement",
    points: 15,
    rarity: "common",
    condition: { type: "points_reached", value: 100, operator: ">=" },
    unlockMessage: "Bạn đã chạm mốc 100 điểm học tập!",
    isHidden: false
  },
  {
    id: "points_500",
    name: "Kho báu điểm số",
    description: "Đạt 500 điểm học tập.",
    icon: "💎",
    color: "#06b6d4",
    category: "engagement",
    points: 50,
    rarity: "rare",
    condition: { type: "points_reached", value: 500, operator: ">=" },
    unlockMessage: "500 điểm là một cột mốc đáng tự hào!",
    isHidden: false
  },
  {
    id: "points_1000",
    name: "Ngôi sao lấp lánh",
    description: "Đạt 1000 điểm học tập.",
    icon: "🌟",
    color: "#f97316",
    category: "engagement",
    points: 100,
    rarity: "epic",
    condition: { type: "points_reached", value: 1000, operator: ">=" },
    unlockMessage: "1000 điểm. Bạn đang tỏa sáng!",
    isHidden: false
  },
  {
    id: "streak_7",
    name: "Chuỗi 7 ngày",
    description: "Duy trì streak học tập 7 ngày liên tiếp.",
    icon: "🔥",
    color: "#ef4444",
    category: "challenge",
    points: 35,
    rarity: "rare",
    condition: { type: "streak_days", value: 7, operator: ">=" },
    unlockMessage: "7 ngày liên tiếp. Rất kiên trì!",
    isHidden: false
  },
  {
    id: "streak_30",
    name: "Vua kiên trì",
    description: "Duy trì streak học tập 30 ngày liên tiếp.",
    icon: "💪",
    color: "#d946ef",
    category: "challenge",
    points: 100,
    rarity: "epic",
    condition: { type: "streak_days", value: 30, operator: ">=" },
    unlockMessage: "Một tháng liên tục. Bạn quá bền bỉ!",
    isHidden: false
  },
  {
    id: "streak_100",
    name: "Không thể ngăn cản",
    description: "Duy trì streak học tập 100 ngày liên tiếp.",
    icon: "🚀",
    color: "#7c3aed",
    category: "challenge",
    points: 300,
    rarity: "legendary",
    condition: { type: "streak_days", value: 100, operator: ">=" },
    unlockMessage: "100 ngày streak. Bạn thật sự không thể ngăn cản!",
    isHidden: true
  },
  {
    id: "level_10",
    name: "Cảnh giới cao thủ",
    description: "Đạt level 10.",
    icon: "🎖️",
    color: "#f59e0b",
    category: "milestone",
    points: 150,
    rarity: "epic",
    condition: { type: "level_reached", value: 10, operator: ">=" },
    unlockMessage: "Bạn đã đạt level 10!",
    isHidden: false
  },
  {
    id: "first_plant",
    name: "Nông dân tập sự",
    description: "Trồng cây đầu tiên trong vườn.",
    icon: "🌱",
    color: "#22c55e",
    category: "engagement",
    points: 10,
    rarity: "common",
    condition: { type: "plants_planted", value: 1, operator: ">=" },
    unlockMessage: "Vườn của bạn đã có cây đầu tiên!",
    isHidden: false
  },
  {
    id: "plants_10",
    name: "Vườn đang lên",
    description: "Trồng tổng cộng 10 cây.",
    icon: "🌿",
    color: "#16a34a",
    category: "engagement",
    points: 30,
    rarity: "rare",
    condition: { type: "plants_planted", value: 10, operator: ">=" },
    unlockMessage: "Bạn đã trồng 10 cây trong vườn!",
    isHidden: false
  },
  {
    id: "plants_50",
    name: "Tỷ phú xanh",
    description: "Trồng tổng cộng 50 cây.",
    icon: "🌳",
    color: "#15803d",
    category: "engagement",
    points: 80,
    rarity: "epic",
    condition: { type: "plants_planted", value: 50, operator: ">=" },
    unlockMessage: "Vườn của bạn đang trở thành một khu rừng nhỏ!",
    isHidden: false
  },
  {
    id: "first_harvest",
    name: "Mùa thu hoạch đầu tiên",
    description: "Thu hoạch cây đầu tiên.",
    icon: "🍎",
    color: "#dc2626",
    category: "engagement",
    points: 15,
    rarity: "common",
    condition: { type: "plants_harvested", value: 1, operator: ">=" },
    unlockMessage: "Bạn đã thu hoạch thành công lần đầu!",
    isHidden: false
  },
  {
    id: "harvest_20",
    name: "Nông dân chính hiệu",
    description: "Thu hoạch 20 lần.",
    icon: "🚜",
    color: "#b45309",
    category: "engagement",
    points: 60,
    rarity: "rare",
    condition: { type: "plants_harvested", value: 20, operator: ">=" },
    unlockMessage: "20 lần thu hoạch. Bạn đang rất mát tay!",
    isHidden: false
  },
  {
    id: "harvest_100",
    name: "Vườn vàng bội thu",
    description: "Thu hoạch 100 lần.",
    icon: "🌽",
    color: "#d97706",
    category: "engagement",
    points: 120,
    rarity: "epic",
    condition: { type: "plants_harvested", value: 100, operator: ">=" },
    unlockMessage: "100 lần thu hoạch. Vườn của bạn quá ổn định!",
    isHidden: false
  },
  {
    id: "gold_500",
    name: "Kho vàng mini",
    description: "Thu thập 500 vàng từ vườn.",
    icon: "💰",
    color: "#f59e0b",
    category: "engagement",
    points: 40,
    rarity: "rare",
    condition: { type: "gold_collected", value: 500, operator: ">=" },
    unlockMessage: "Vườn của bạn bắt đầu sinh lời rõ ràng!",
    isHidden: false
  },
  {
    id: "gold_1000",
    name: "Nhà giàu nông trại",
    description: "Thu thập 1000 vàng từ vườn.",
    icon: "🏆",
    color: "#fbbf24",
    category: "milestone",
    points: 100,
    rarity: "epic",
    condition: { type: "gold_collected", value: 1000, operator: ">=" },
    unlockMessage: "1000 vàng từ vườn. Rất ấn tượng!",
    isHidden: false
  },
  {
    id: "watered_20",
    name: "Bàn tay mát",
    description: "Tưới cây 20 lần.",
    icon: "💧",
    color: "#0ea5e9",
    category: "engagement",
    points: 20,
    rarity: "common",
    condition: { type: "plants_watered", value: 20, operator: ">=" },
    unlockMessage: "Cây cối của bạn đang được chăm sóc rất tốt!",
    isHidden: false
  },
  {
    id: "watered_100",
    name: "Siêu nhân tưới cây",
    description: "Tưới cây 100 lần.",
    icon: "🌧️",
    color: "#0284c7",
    category: "engagement",
    points: 40,
    rarity: "rare",
    condition: { type: "plants_watered", value: 100, operator: ">=" },
    unlockMessage: "100 lần tưới cây. Bạn rất có tâm với khu vườn!",
    isHidden: false
  },
  {
    id: "decoration_master",
    name: "Nghệ nhân trang trí",
    description: "Đặt 20 vật trang trí trong vườn.",
    icon: "🎨",
    color: "#ec4899",
    category: "engagement",
    points: 50,
    rarity: "rare",
    condition: { type: "decorations_placed", value: 20, operator: ">=" },
    unlockMessage: "Vườn của bạn đã có phong cách riêng rất rõ ràng!",
    isHidden: false
  }
].map((achievement) => ({
  ...achievement,
  isActive: achievement.isActive !== false
}));

module.exports = {
  ACHIEVEMENT_DEFINITIONS
};
